<a href="https://colab.research.google.com/github/HowardHNguyen/Data_Science_for_Marketing_Solutions/blob/main/EDA_Preparing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Before exploring and analyzing tabular data, we sometimes will be required to prepare the data for analysis. This preparation can come in the form of data transformation, aggregation, or cleanup. In Python, the pandas library helps us to achieve this through several modules. The preparation steps for tabular data are never a one-size-fits-all approach. They are typically determined by the structure of our data, that is, the rows, columns, data types, and data values.

Kaggle provides the Marketing Campaign data for public use at https://www.kaggle.com/datasets/imakash3011/customer-personality-analysis. In this chapter, we use both the full dataset and samples of the dataset for the different recipes. The data is also available in the repository. The data in Kaggle appears in a single-column format, but the data in the repository was transformed into a multiple-column format for easy usage in pandas.

#### Import relevant libraries

In [1]:
import numpy as np
import pandas as pd

#### Load data into dataframe

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
marketing_data = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign.csv")

#### Inspect the dataframe

In [7]:
marketing_data.head(5)

,Unnamed: 0,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,...,7,0,0,0,0,0,0,3,11,1
1,1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,...,5,0,0,0,0,0,0,3,11,0
2,2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,...,4,0,0,0,0,0,0,3,11,0
3,3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,...,6,0,0,0,0,0,0,3,11,0
4,4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,...,5,0,0,0,0,0,0,3,11,0

In [8]:
marketing_data.columns

Index(['Unnamed: 0', 'ID', 'Year_Birth', 'Education', 'Marital_Status',
       'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'Recency', 'MntWines',
       'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

In [9]:
marketing_data.shape

(2240, 30)

In [11]:
marketing_data = marketing_data[['ID','Year_Birth', 'Education','Marital_Status','Income','Kidhome', 'Teenhome', 'Dt_Customer','Recency','NumStorePurchases', 'NumWebVisitsMonth']]
marketing_data

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5
...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,4,5
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,5,7
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,13,6
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,10,3
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,4,7

Inspect the data. Check the first few rows and use transpose (T) to show more information. Also, check the data types as well as the number of columns and rows:

In [14]:
marketing_data.head(6).T

,0,1,2,3,4,5
ID,5524,2174,4141,6182,5324,7446
Year_Birth,1957,1954,1965,1984,1981,1967
Education,Graduation,Graduation,Graduation,Graduation,PhD,Master
Marital_Status,Single,Single,Together,Together,Married,Together
Income,58138.0,46344.0,71613.0,26646.0,58293.0,62513.0
Kidhome,0,1,0,1,1,0
Teenhome,0,1,0,0,0,1
Dt_Customer,04-09-2012,08-03-2014,21-08-2013,10-02-2014,19-01-2014,09-09-2013
Recency,58,38,26,26,94,16
NumStorePurchases,4,2,10,4,6,10
NumWebVisitsMonth,7,5,4,6,5,6

In [15]:
marketing_data.dtypes

ID                     int64
Year_Birth             int64
Education             object
Marital_Status        object
Income               float64
Kidhome                int64
Teenhome               int64
Dt_Customer           object
Recency                int64
NumStorePurchases      int64
NumWebVisitsMonth      int64
dtype: object

In [16]:
marketing_data.shape

(2240, 11)

## Find the average number of store purchases of customers
When we group data, we are aggregating the data by category. This can be very useful especially when we need to get a high-level view of a detailed dataset. Typically, to group a dataset, we need to identify the column/category to group by, the column to aggregate by, and the specific aggregation to be done. The column/category to group by is usually a categorical column while the column to aggregate by is usually a numeric column. The aggregation to be done can be a count, sum, minimum, maximum, and so on. We can also perform aggregation such as count directly on the categorical column we group by

In [19]:
marketing_data.groupby('Kidhome')['NumStorePurchases'].mean()

Kidhome
0    7.217324
1    3.863181
2    3.437500
Name: NumStorePurchases, dtype: float64

In [18]:
marketing_data.groupby('Teenhome')['NumStorePurchases'].mean()

Teenhome
0    5.637306
1    5.938835
2    6.250000
Name: NumStorePurchases, dtype: float64

In [20]:
marketing_data.groupby('Year_Birth')['NumStorePurchases'].mean()

Year_Birth
1893    2.000000
1899    4.000000
1900    2.000000
1940    4.000000
1941    5.000000
1943    8.857143
1944    8.285714
1945    6.500000
1946    7.562500
1947    7.812500
1948    6.190476
1949    7.033333
1950    5.241379
1951    6.511628
1952    6.557692
1953    5.885714
1954    6.220000
1955    6.632653
1956    6.963636
1957    5.372093
1958    6.301887
1959    5.941176
1960    6.673469
1961    6.444444
1962    7.068182
1963    5.600000
1964    6.119048
1965    5.918919
1966    5.780000
1967    6.000000
1968    5.705882
1969    5.774648
1970    6.012987
1971    5.333333
1972    5.506329
1973    4.540541
1974    5.536232
1975    5.710843
1976    5.516854
1977    5.115385
1978    5.285714
1979    5.679245
1980    5.307692
1981    5.358974
1982    5.422222
1983    4.619048
1984    4.342105
1985    5.093750
1986    4.738095
1987    6.037037
1988    5.793103
1989    5.833333
1990    4.666667
1991    6.800000
1992    5.153846
1993    5.800000
1994    9.333333
1995    7.200000
1996    2.500000
Name: NumStorePurchases, dtype: float64

## Appending data - To add rows in dataset
Sometimes, we may be analyzing multiple datasets that have a similar structure or samples of the same dataset. While analyzing our datasets, we may need to append them together into a new single dataset. When we append datasets, we stitch the datasets along the rows. For example, if we have 2 datasets containing 1,000 rows and 20 columns each, the appended data will contain 2,000 rows and 20 columns. The rows typically increase while the columns remain the same. The datasets are allowed to have a different number of rows but typically should have the same number of columns to avoid errors after appending.

We will use the 'concat' method in pandas to append data.

In [22]:
marketing_sample1 = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign_append1.csv")
marketing_sample2 = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign_append2.csv")

In [23]:
marketing_sample1 = marketing_sample1[['ID', 'Year_Birth','Education','Marital_Status','Income', 'Kidhome','Teenhome','Dt_Customer', 'Recency','NumStorePurchases', 'NumWebVisitsMonth']]
marketing_sample2 = marketing_sample2[['ID', 'Year_Birth','Education','Marital_Status','Income', 'Kidhome','Teenhome','Dt_Customer', 'Recency','NumStorePurchases', 'NumWebVisitsMonth']]

In [24]:
# take a look at the two datasets
marketing_sample1.head(5).T

                            0           1           2           3           4
ID                       5524        2174        4141        6182        5324
Year_Birth               1957        1954        1965        1984        1981
Education          Graduation  Graduation  Graduation  Graduation         PhD
Marital_Status         Single      Single    Together    Together     Married
Income                58138.0     46344.0     71613.0     26646.0     58293.0
Kidhome                     0           1           0           1           1
Teenhome                    0           1           0           0           0
Dt_Customer        04/09/2012  08/03/2014  21/08/2013  10/02/2014  19/01/2014
Recency                    58          38          26          26          94
NumStorePurchases           4           2          10           4           6
NumWebVisitsMonth           7           5           4           6           5

In [25]:
marketing_sample2.head(5).T

                            0           1           2           3           4
ID                       9135         466        9135       10623        8151
Year_Birth               1950        1944        1950        1961        1990
Education          Graduation  Graduation  Graduation      Master       Basic
Marital_Status       Together     Married    Together    Together     Married
Income                  27203       65275       27203       48330       24279
Kidhome                     1           0           1           0           0
Teenhome                    1           0           1           1           0
Dt_Customer        06/08/2012  03/04/2013  06/08/2012  15/11/2013  29/12/2012
Recency                    92           9          92           2           6
NumStorePurchases           2          13           2           3           3
NumWebVisitsMonth           8           2           8           5           8

In [26]:
marketing_sample1.shape

(500, 11)

In [27]:
marketing_sample2.shape

(500, 11)

In [28]:
append_data = pd.concat([marketing_sample1, marketing_sample2])

In [29]:
append_data.shape

(1000, 11)

In [30]:
append_data.head(5).T

                            0           1           2           3           4
ID                       5524        2174        4141        6182        5324
Year_Birth               1957        1954        1965        1984        1981
Education          Graduation  Graduation  Graduation  Graduation         PhD
Marital_Status         Single      Single    Together    Together     Married
Income                58138.0     46344.0     71613.0     26646.0     58293.0
Kidhome                     0           1           0           1           1
Teenhome                    0           1           0           0           0
Dt_Customer        04/09/2012  08/03/2014  21/08/2013  10/02/2014  19/01/2014
Recency                    58          38          26          26          94
NumStorePurchases           4           2          10           4           6
NumWebVisitsMonth           7           5           4           6           5

## Concatenating data - to add columns to dataset
Sometimes, we may need to stitch multiple datasets or samples of the same dataset by columns and not rows. This is where we concatenate our data. While appending stitches rows of data together, concatenating stitches columns together to provide a single dataset. For example, if we have 2 datasets containing 1,000 rows and 20 columns each, the concatenated data will contain 1,000 rows and 40 columns. The columns typically increase while the rows remain the same. The datasets are allowed to have a different number of columns but typically should have the same number of rows to avoid errors after concatenating.

In [34]:
concat_data_1 = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign_concat1.csv")
concat_data_2 = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign_concat2.csv")

In [35]:
concatenated_data = pd.concat([concat_data_1, concat_data_2], axis=1)

In [36]:
# inspect the shape of the result and first few rows
concatenated_data.head(5).T

                              0           1           2           3        4
ID                         5524        2174        4141        6182     5324
Year_Birth                 1957        1954        1965        1984     1981
Education            Graduation  Graduation  Graduation  Graduation      PhD
Marital_Status           Single      Single    Together    Together  Married
Income                  58138.0     46344.0     71613.0     26646.0  58293.0
NumDealsPurchases             3           2           1           2        5
NumWebPurchases               8           1           8           2        5
NumCatalogPurchases          10           1           2           0        3
NumStorePurchases             4           2          10           4        6
NumWebVisitsMonth             7           5           4           6        5

In [38]:
concat_data_1.shape

(2240, 5)

In [41]:
concat_data_1.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income'], dtype='object')

In [39]:
concat_data_2.shape

(2240, 5)

In [42]:
concat_data_2.columns

Index(['NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases',
       'NumStorePurchases', 'NumWebVisitsMonth'],
      dtype='object')

In [37]:
concatenated_data.shape

(2240, 10)

In [40]:
concatenated_data.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income',
       'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases',
       'NumStorePurchases', 'NumWebVisitsMonth'],
      dtype='object')

## Merging Data
Merging sounds a bit like concatenating our dataset; however, it is quite different. To merge datasets, we need to have a common field in both datasets on which we can perform a merge.

If you are familiar with the SQL or join commands, then you are probably familiar with merging data. Usually, data from relational databases will require merging operations. Relational databases typically contain tabular data and account for a significant proportion of data found in many organizations.

In [43]:
merge_data1 = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign_merge1.csv")
merge_data2 = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign_merge2.csv")
#

In [44]:
merge_data1.head(5).T

                     0           1           2           3     4
ID                5524        2174        4141        6182  5324
Year_Birth        1957        1954        1965        1984  1981
Education   Graduation  Graduation  Graduation  Graduation   PhD

In [47]:
merge_data1.shape

(2240, 3)

In [45]:
merge_data2.head(5).T

                      0        1         2         3        4
ID                 5524     2174      4141      6182     5324
Marital_Status   Single   Single  Together  Together  Married
Income          58138.0  46344.0   71613.0   26646.0  58293.0

In [46]:
merged_data = pd.merge(merge_data1, merge_data2, on='ID')

In [48]:
merged_data.head(5)

     ID  Year_Birth   Education Marital_Status   Income
0  5524        1957  Graduation         Single  58138.0
1  2174        1954  Graduation         Single  46344.0
2  4141        1965  Graduation       Together  71613.0
3  6182        1984  Graduation       Together  26646.0
4  5324        1981         PhD        Married  58293.0

In [49]:
merged_data.shape

(2240, 5)

## Sorting Data
When we sort data, we arrange it in a specific sequence. This specific sequence typically helps us to spot patterns very quickly. To sort a dataset, we usually must specify one or more columns to sort by and specify the order to sort by (ascending or descending order).

In pandas, the sort_values method can be used to sort a dataset.

In [50]:
marketing_data = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign.csv")
marketing_data = marketing_data[['ID','Year_Birth', 'Education','Marital_Status','Income','Kidhome', 'Teenhome', 'Dt_Customer','Recency','NumStorePurchases', 'NumWebVisitsMonth']]

In [51]:
marketing_data.head(5).T

                            0           1           2           3           4
ID                       5524        2174        4141        6182        5324
Year_Birth               1957        1954        1965        1984        1981
Education          Graduation  Graduation  Graduation  Graduation         PhD
Marital_Status         Single      Single    Together    Together     Married
Income                58138.0     46344.0     71613.0     26646.0     58293.0
Kidhome                     0           1           0           1           1
Teenhome                    0           1           0           0           0
Dt_Customer        04-09-2012  08-03-2014  21-08-2013  10-02-2014  19-01-2014
Recency                    58          38          26          26          94
NumStorePurchases           4           2          10           4           6
NumWebVisitsMonth           7           5           4           6           5

In [58]:
sorted_data_income = marketing_data.sort_values(by='Income', ascending=False)
sorted_data_income.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
2233,9432,1977,Graduation,Together,666666.0,1,0,02-06-2013,23,3,6
617,1503,1976,PhD,Together,162397.0,1,1,03-06-2013,31,1,1
687,1501,1982,PhD,Married,160803.0,0,0,04-08-2012,21,1,0
1300,5336,1971,Master,Together,157733.0,1,0,04-06-2013,37,1,1
164,8475,1973,PhD,Married,157243.0,0,1,01-03-2014,98,0,0

In [61]:
# Sort customers based on the numder of store purchases in descending order
sorted_data_purchases = marketing_data.sort_values(by='NumStorePurchases', ascending=False)
sorted_data_purchases.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
1187,9855,1952,PhD,Single,62000.0,0,1,25-08-2013,25,13,4
803,9930,1944,PhD,Single,82716.0,0,0,05-11-2013,8,13,2
1144,819,1945,Graduation,Widow,63285.0,0,0,05-11-2013,84,13,3
286,10983,1952,Graduation,Together,75278.0,0,0,29-01-2013,17,13,3
1150,1453,1943,PhD,Widow,57513.0,0,0,06-07-2013,59,13,6

In [63]:
# Inspect the result. Subset for relevant columns
sorted_data_purchases[['ID','NumStorePurchases']].head()

         ID  NumStorePurchases
1187   9855                 13
803    9930                 13
1144    819                 13
286   10983                 13
1150   1453                 13

In [70]:
sorted_data_income[['ID','Income']].head()

        ID    Income
2233  9432  666666.0
617   1503  162397.0
687   1501  160803.0
1300  5336  157733.0
164   8475  157243.0

In [72]:
# Sort customers based on the education feature in descending order
sorted_data_edu = marketing_data.sort_values(by='Education', ascending=False)
sorted_data_edu.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,4,7
420,5929,1973,PhD,Married,37401.0,1,0,06-05-2014,14,3,7
412,7030,1955,PhD,Married,66465.0,0,1,30-03-2013,1,12,6
1955,6428,1950,PhD,Widow,76842.0,0,0,03-05-2014,37,7,0
1954,5626,1964,PhD,Single,61798.0,0,0,23-11-2013,13,9,4

In [76]:
sorted_data_edu[['Year_Birth','Education','NumStorePurchases']].head()

      Year_Birth Education  NumStorePurchases
2239        1954       PhD                  4
420         1973       PhD                  3
412         1955       PhD                 12
1955        1950       PhD                  7
1954        1964       PhD                  9

## Categorizing Data
When we refer to categorizing data, we are specifically referring to binning, bucketing, or cutting a dataset. Binning involves grouping the numeric values in a dataset into smaller intervals called bins or buckets. When we bin numerical values, each bin becomes a categorical value. Bins are very useful because they can provide us with insights that may have been difficult to spot if we had worked directly with individual numerical values. Bins don’t always have equal intervals; the creation of bins is dependent on our understanding of a dataset.

Binning can also be used to address outliers or reduce the effect of observation errors. Outliers are unusually high or unusually low data points that are far from other data points in our dataset. They typically lead to anomalies in the output of our analysis. Binning can reduce this effect by placing the range of numerical values including the outliers into specific buckets, thereby making the values categorical. A common example of this is when we convert age values into age groups. Outlier ages such as 0 or 150 can fall into a less than age 18 bin and greater than age 80 bin respectively.

In pandas, the cut method can be used to bin a dataset.

In [78]:
# categorize the number of store purchases into high, moderate, and low categories
marketing_data['bins'] = pd.cut(x=marketing_data['NumStorePurchases'], bins=[0,4,8,13], labels=['Low','Medium','High'])

In [79]:
# inspect the result. Subset for relevant columns
marketing_data[['ID','NumStorePurchases','bins']].head()

     ID  NumStorePurchases    bins
0  5524                  4     Low
1  2174                  2     Low
2  4141                 10    High
3  6182                  4     Low
4  5324                  6  Medium

## Removing suplicate data
Duplicate data can be very misleading and can lead us to wrong conclusions about patterns and the distribution of our data. Therefore, it is very important to address duplicate data within our dataset before embarking on any analysis. Performing a quick duplicate check is good practice in EDA. When working with tabular datasets, we can identify duplicate values in specific columns or duplicate records (across multiple columns). A good understanding of our dataset and the domain will give us insight into what should be considered a duplicate. In pandas, the drop_duplicates method can help us with handling duplicate values or records within our dataset.

In [80]:
marketing_data = marketing_data[['Education', 'Marital_Status', 'Kidhome','Teenhome']]

In [81]:
marketing_data.head()

    Education Marital_Status  Kidhome  Teenhome
0  Graduation         Single        0         0
1  Graduation         Single        1         1
2  Graduation       Together        0         0
3  Graduation       Together        1         0
4         PhD        Married        1         0

In [82]:
marketing_data.shape

(2240, 4)

In [83]:
# remove duplicate across the four columns in this dataset
marketing_data_duplicates = marketing_data.drop_duplicates()

In [84]:
# inspect the result
marketing_data_duplicates.shape

(135, 4)

In [85]:
marketing_data_duplicates.head()

    Education Marital_Status  Kidhome  Teenhome
0  Graduation         Single        0         0
1  Graduation         Single        1         1
2  Graduation       Together        0         0
3  Graduation       Together        1         0
4         PhD        Married        1         0

## Dropping data rows and columns
When working with tabular data, we may have reason to drop some rows or columns within our dataset. Sometimes, we may need to drop columns or rows either because they are erroneous or irrelevant. In pandas, we have the flexibility to drop a single row/column or multiple rows/columns. We can use the drop method to achieve this.

In [86]:
marketing_data = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign.csv")

In [88]:
marketing_data = marketing_data[['ID','Year_Birth', 'Kidhome', 'Teenhome']]

In [89]:
marketing_data.head()

     ID  Year_Birth  Kidhome  Teenhome
0  5524        1957        0         0
1  2174        1954        1         1
2  4141        1965        0         0
3  6182        1984        1         0
4  5324        1981        1         0

In [90]:
marketing_data.shape

(2240, 4)

In [92]:
# from os import replace
# delete a specific row at index value 1
marketing_data.drop(labels=[1], axis=0, replace=True)

KeyError: '[1] not found in axis'

In [93]:
marketing_data.head()

     ID  Year_Birth  Kidhome  Teenhome
0  5524        1957        0         0
2  4141        1965        0         0
3  6182        1984        1         0
4  5324        1981        1         0
5  7446        1967        0         1

In [95]:
# delete a single column
marketing_data.drop(labels=['Kidhome'], axis=1)

         ID  Year_Birth  Teenhome
0      5524        1957         0
2      4141        1965         0
3      6182        1984         0
4      5324        1981         0
5      7446        1967         1
...     ...         ...       ...
2235  10870        1967         1
2236   4001        1946         1
2237   7270        1981         0
2238   8235        1956         1
2239   9405        1954         1

[2239 rows x 3 columns]

## Replacing data
Replacing values in rows or columns is a common practice when working with tabular data. There are many reasons why we may need to replace specific values within a dataset. Python provides the flexibility to replace single values or multiple values within our dataset. We can use the replace method to achieve this.

In [96]:
marketing_data = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign.csv")
marketing_data = marketing_data[['ID','Year_Birth', 'Kidhome', 'Teenhome']]
# inspect the dataset
marketing_data.head()

     ID  Year_Birth  Kidhome  Teenhome
0  5524        1957        0         0
1  2174        1954        1         1
2  4141        1965        0         0
3  6182        1984        1         0
4  5324        1981        1         0

In [97]:
# replace the values in Teenhome with has teen and has no teen
marketing_data['Teenhome_replaced'] = marketing_data['Teenhome'].replace([0,1,2], ['has no teen','has teen','has teen'])
marketing_data[['Teenhome','Teenhome_replaced']].head()

   Teenhome Teenhome_replaced
0         0       has no teen
1         1          has teen
2         0       has no teen
3         0       has no teen
4         0       has no teen

## Changing a data format
When analyzing or exploring data, the type of analysis we perform on our data is highly dependent on the data formats or data types within our dataset. Typically, numerical data requires specific analytical techniques, while categorical data requires other analytical techniques. Hence, it is important that data types are properly captured before analysis commences.

In pandas, the dtypes attribute helps us to inspect the data types within our dataset, while the astype attribute helps us to convert our dataset between various data types.

In [99]:
marketing_data = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign.csv")

In [100]:
marketing_data = marketing_data[['ID','Year_Birth', 'Marital_Status', 'Income']]
marketing_data

         ID  Year_Birth Marital_Status   Income
0      5524        1957         Single  58138.0
1      2174        1954         Single  46344.0
2      4141        1965       Together  71613.0
3      6182        1984       Together  26646.0
4      5324        1981        Married  58293.0
...     ...         ...            ...      ...
2235  10870        1967        Married  61223.0
2236   4001        1946       Together  64014.0
2237   7270        1981       Divorced  56981.0
2238   8235        1956       Together  69245.0
2239   9405        1954        Married  52869.0

[2240 rows x 4 columns]

In [101]:
marketing_data.isnull().sum()

ID                 0
Year_Birth         0
Marital_Status     0
Income            24
dtype: int64

In [102]:
# fill NAs in the Income column
marketing_data['Income'] = marketing_data['Income'].fillna(0)

In [103]:
marketing_data.isnull().sum()

ID                0
Year_Birth        0
Marital_Status    0
Income            0
dtype: int64

In [104]:
# change the data type of the Income column from float to int
marketing_data['Income_changed'] = marketing_data['Income'].astype(int)
# inspect the output
marketing_data[['Income','Income_changed']].head()

    Income  Income_changed
0  58138.0           58138
1  46344.0           46344
2  71613.0           71613
3  26646.0           26646
4  58293.0           58293

In [106]:
marketing_data[['Income','Income_changed']].dtypes

Income            float64
Income_changed      int64
dtype: object

## Dealing with missing values
Dealing with missing values is a common problem we will typically face when analyzing data. A missing value is a value within a field or variable that is not present, even though it is expected to be. There are several reasons why this could have happened, but a common reason is that the data value wasn’t provided at the point of data collection. As we explore and analyze data, missing values can easily lead to inaccurate or biased conclusions; therefore, they need to be taken care of. Missing values are typically represented by blank spaces, but in pandas, they are represented by NaN.

Several techniques can be used to deal with missing values. In this recipe, we will focus on dropping missing values using the dropna method in pandas.

In [109]:
marketing_data = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch2/Data/marketing_campaign.csv")

In [110]:
marketing_data = marketing_data[['ID','Year_Birth', 'Marital_Status', 'Income']]
marketing_data.head()

     ID  Year_Birth Marital_Status   Income
0  5524        1957         Single  58138.0
1  2174        1954         Single  46344.0
2  4141        1965       Together  71613.0
3  6182        1984       Together  26646.0
4  5324        1981        Married  58293.0

In [111]:
marketing_data.isnull().sum()

ID                 0
Year_Birth         0
Marital_Status     0
Income            24
dtype: int64

In [112]:
df_drop_na = marketing_data.dropna(how = 'any')
df_drop_na.isnull().sum()

ID                0
Year_Birth        0
Marital_Status    0
Income            0
dtype: int64

In [113]:
df_drop_na.shape

(2216, 4)